// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("WebApplication1.Models.CourseCategory", b =>
                {
                    b.Property<int>("courseCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .HasColumnType("TEXT");

                    b.HasKey("courseCategoryId");

                    b.ToTable("CourseCategoriesData");
                });

            modelBuilder.Entity("WebApplication1.Models.Courses", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ccId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("courseCreation")
                        .HasColumnType("TEXT");

                    b.Property<string>("courseDesc")
                        .HasColumnType("TEXT");

                    b.Property<string>("courseName")
                        .HasColumnType("TEXT");

                    b.Property<string>("courseRating")
                        .HasColumnType("TEXT");

                    b.Property<string>("courseUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("courseId");

                    b.ToTable("Courses");
                });
#pragma warning restore 612, 618
        }
    }
}
